### ISSUE TITLE
Demo refreshing the page logs you out

### ISSUE THREAD

**Issue by jericopulvera** [sandrinodimattia/use-auth0-hooks#13]
https://nextjs-spa-auth0-demo.now.sh/

Can you explain why is this the case?

**Comment by Yezuz05** [comment]
Please I have this same issue with my app, how can we persist the user's authentication after the page is refreshed.

**Comment by jericopulvera** [comment]
https://community.auth0.com/t/getting-logged-out-after-refreshing-on-localhost-react-js-spa/28474
