### ISSUE TITLE
accessToken is not a valid jwt?

### ISSUE THREAD

**Issue by zachurich** [sandrinodimattia/use-auth0-hooks#16]
To get `accessToken` to be defined, you have to pass `true` into the `useAuth` hook. Passing in an object with `audience` doesn't appear to have any effect. Even when `accessToken` IS defined, it isn't a valid jwt, so you can't use it as a Bearer token in any API calls to other Auth0-wrapped backends. Is this library supposed to be production ready?

**Comment by Mad-Kat** [comment]
It should work when you pass `useAuth({audience:"YOUR-API-AUDIENCE",scope:""})`, where "YOUR-API-AUDIENCE" is a custom API, which you made in Auth0. So the application settings alone won't generate a valid jwt access token but an opaque access token. If you define the audience to be your custom api, then auth0 will send you a valid jwt access token.

Read it here: [https://auth0.com/docs/tokens/guides/get-access-tokens](https://auth0.com/docs/tokens/guides/get-access-tokens)
