### ISSUE TITLE
Error: Auth0Client was not initialized

### ISSUE THREAD

**Issue by bbortt** [sandrinodimattia/use-auth0-hooks#2]
Hi
I tried using your hooks in a very small project (static pages), following the example. Login works fine, as soon as I hit `F5` the authentication failes: `Error: Auth0Client was not initialized`.
Therefore I've cloned the example itself and ended up in the same error.
I've tried Chrome as well as Firefox. Have you experienced similar issues at any time?
BR, Timon

**Comment by sandrinodimattia** [comment]
Hi @bbortt,

I'm unable to reproduce it myself. Can you try it here: https://nextjs-spa-auth0-demo.now.sh

Also, can you share specific browser versions you have tested with? And which version of `use-auth0-hooks` are you using?

**Comment by goszczynskip** [comment]
I had the same problem as @bbortt. In my case it was caused by setting something else to `redirectUrl` on `Auth0Provider` than `http://localhost:3000/authorize`. This happend probably because it was only acceptable redirectUri set in auth0 admin panel. It would be nice to get a more descriptive error though.

**Comment by bbortt** [comment]
no, redirect url is set correctly. maybe its the wrong client type. it is single page application, right? I remember it stated out something about cross domain access to cookies in the console. I'll give more details tomorrow.

**Comment by bbortt** [comment]
Ok, I found the error in the Auth0 logs.. was a bit misleading as the original HTTP response just stated out code 400 "whoops, something went wrong". But then I found this:
```
"error": {
      "message": "The specified redirect_uri 'http://localhost:3000/app' does not have a registered origin.",
      "oauthError": "invalid_request",
      "type": "request-error"
    }
```
Seems like you have to register "http://localhost:3000" (or whatever local port you're using) as allowed origin in your application.
Works like a charm now! Thx :)
