### ISSUE TITLE
Error in the README/docs

### ISSUE THREAD

**Issue by ScorpIan555** [sandrinodimattia/use-auth0-hooks#3]
In the README, you advise:

import { useAuth0 } from 'use-auth0-hooks'

Results in a runtime error because it appears the correct module name is simply 'useAuth'.  I was able to figure it out easy enough by checking into your repo but it probably needs to be fixed.

**Comment by russelh15** [comment]
Ran into this issue as well. Thanks for this @ScorpIan555 !

**Comment by sandrinodimattia** [comment]
Fixed, thanks!
