### ISSUE TITLE
Feature comparison

### ISSUE THREAD

**Issue by vgrafe** [sandrinodimattia/use-auth0-hooks#4]
Hi! 

Happy to have found your repo... I wish I discovered it sooner! Starred a week ago, and I finally have some time to try it out. 

I am interested in the NextJS use case. Can you help me have a good idea on how it compares with https://github.com/auth0/nextjs-auth0 with its usage and features?

Thanks!

**Comment by sandrinodimattia** [comment]
Hi @vgrafe, all the details are in this blog post: https://auth0.com/blog/ultimate-guide-nextjs-authentication-auth0/

This package will allow you to create an SPA where authentication is handled by the browser and tokens are stored in the browser.

If you have a backend that can create a session, then you'll benefit from https://github.com/auth0/nextjs-auth0 as you don't need to manage anything on the client side.

**Comment by vgrafe** [comment]
My goal is to avoid having to write a custom server (`server.js`) to keep close to nextjs's pit of success. 

`nextjs-auth0` has been pretty helpful with so far with some hiccups (but functionalities are added pretty fast), the last one being no cross-subdomain support.

I am eager to see how your `use-auth0-hooks` compare. Thank you for the links, I hope I get some time to try it out before the weekend!

**Comment by vgrafe** [comment]
Oh, I see. Looks like this is very client-side focused, so it can't be used with SSR, regardless of the presence of a custom server. I hope no one pays attention to my above comment.
