### ISSUE TITLE
Tv Shows API link is broken on the docs

### ISSUE THREAD

**Issue by brunoreis** [sandrinodimattia/use-auth0-hooks#9]
https://github.com/sandrinodimattia/use-auth0-hooks/tree/master/examples/nextjs-spa/README.md links to:

https://github.com/sandrinodimattia/use-auth0-hooks/blob/master/examples/tv-shows-ap

should be

https://github.com/sandrinodimattia/use-auth0-hooks/blob/master/examples/tv-shows-api

**Comment by sandrinodimattia** [comment]
Thanks, fixed!
